USE BOOKSTORE;

DROP TABLE IF EXISTS REVIEWS;
DROP TABLE IF EXISTS DETAILS;
DROP TABLE IF EXISTS INVOICES;
DROP TABLE IF EXISTS CLIENTS;
DROP TABLE IF EXISTS INVENTORY;

CREATE TABLE REVIEWS  (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ISBN varchar(13),
  CLIENTNUM int,
  DATEOFREVIEW timestamp DEFAULT CURRENT_TIMESTAMP,
  RATING int DEFAULT 0,
  REVIEWTEXT text,
  APPROVALSTATUS boolean DEFAULT false
) ENGINE=InnoDB;

CREATE TABLE DETAILS  (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  INVOICENUM int,
  ISBN varchar(13),  
  BOOKPRICE decimal(5,2)
) ENGINE=InnoDB;

CREATE TABLE INVOICES (
  INVOICENUM int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DATEOFSALE timestamp DEFAULT CURRENT_TIMESTAMP,
  CLIENTNUM int,
  NETPRICE decimal(7,2),
  GSTRATE decimal(3,2),
  TOTALPRICE decimal(7,2)
) ENGINE=InnoDB;

CREATE TABLE INVENTORY (
  ISBN varchar(13) NOT NULL PRIMARY KEY,
  DATEOFENTRY timestamp DEFAULT CURRENT_TIMESTAMP,
  TITLE varchar(75),
  AUTHORS varchar(225),
  PUBLISHER varchar(75),
  DATEOFPUBLICATION timestamp DEFAULT CURRENT_TIMESTAMP,
  PAGES int DEFAULT 0,
  GENRE varchar(75),
  IMAGE varchar(75),
  COST decimal(5,2),
  LIST decimal(5,2),
  REMOVALSTATUS boolean DEFAULT false
) ENGINE=InnoDB;

CREATE TABLE CLIENTS(
  CLIENTNUM int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EMAIL varchar(50),
  TITLE varchar(10),
  LASTNAME varchar(50),
  FIRSTNAME varchar(50),
  COMPANYNAME varchar(50),
  ADDRESS1 varchar(50),
  ADDRESS2 varchar(50),
  CITY varchar(50),
  PROVINCE varchar(2),
  COUNTRY varchar(3),
  POSTALCODE varchar(7),
  TELHOME varchar(14),
  TELCEL varchar(14)
) ENGINE=InnoDB;

-- Make the field EMAIL indexed and unique
ALTER TABLE CLIENTS ADD UNIQUE (EMAIL); 
-- Add indexes for commonly searched columns 
ALTER TABLE INVENTORY ADD INDEX(TITLE);
ALTER TABLE INVENTORY ADD INDEX(AUTHORS);
ALTER TABLE INVENTORY ADD INDEX(PUBLISHER);
ALTER TABLE INVENTORY ADD INDEX(GENRE);

-- Add the foreign keys
ALTER TABLE DETAILS ADD CONSTRAINT FK_ISBNDETAILSINVENTORY FOREIGN KEY (ISBN) REFERENCES INVENTORY(ISBN);
ALTER TABLE DETAILS ADD CONSTRAINT FK_INVOICENUMDETAILSINVOICES FOREIGN KEY (INVOICENUM) REFERENCES INVOICES(INVOICENUM);

ALTER TABLE REVIEWS ADD CONSTRAINT FK_ISBNREVIEWSINVENTORY FOREIGN KEY (ISBN) REFERENCES INVENTORY(ISBN);
ALTER TABLE REVIEWS ADD CONSTRAINT FK_ISBNREVIEWSCLIENT FOREIGN KEY (CLIENTNUM) REFERENCES CLIENTS(ClIENTNUM);

ALTER TABLE INVOICES ADD CONSTRAINT FK_CLIENTNUMINVOICESCLIENT FOREIGN KEY (CLIENTNUM) REFERENCES CLIENTS(ClIENTNUM);




  
  
  
  
  
  
  
  
  

